### ISSUE TITLE
[Package based install] Copy default community requirements.yml task fails - Destination / not writable

### ISSUE THREAD

**Issue by Spredzy** [ansible/galaxy_collection_archived#8]
The following task fails if one is using a package based deployment

```
- name: Copy default community requirements.yml
  copy:
    src: '{{ role_path }}/files/requirements.yml'
    dest: '{{ pulp_install_dir }}/requirements.yml'
    mode: '0660'
  become: true
  become_user: '{{ pulp_user }}'
```

Reason is default `pulp_install_dir` (ie. `/usr/local/lib/pulp`) doesn't exist in package based install. And if we override the playbook with proper[1] `pulp_install_dir` (ie. `/usr`) then the `{{ pulp_user }}` doesn't have the permissions to write the file on the directory.

```
[2020-09-15T20:26:38.071Z]     TASK [ansible.galaxy_collection.post_install_config : Copy default community requirements.yml] ***
[2020-09-15T20:26:38.072Z]     fatal: [ec2-18-207-206-14.compute-1.amazonaws.com]: FAILED! => {"changed": false, "checksum": "495350a40bd3dc9d042194d152a2f6a0b5e96f35", "msg": "Destination / not writable"}
```

[1] https://github.com/pulp/pulp_installer/blob/16c11e2a6f66fdec10e759dd752af1785185c234/roles/pulp_common/defaults/main.yml#L9

**Comment by Spredzy** [comment]
This is what I came up with to temporarily resolve the problem (you might come up with a better idea):

```
- name: create temporary build directory
  tempfile:
    state: directory
    prefix: automationhub
  become: true
  become_user: '{{ pulp_user }}'
  register: automationhub_tempdir

- name: Copy default community requirements.yml
  copy:
    src: '{{ role_path }}/files/requirements.yml'
    dest: '{{ automationhub_tempdir.path }}/requirements.yml'
    mode: '0660'
  become: true
  become_user: '{{ pulp_user }}'

- name: Configure Community remote
  command: >
    {{ pulp_install_dir }}/bin/pulpcore-manager
     create-remote
     community
     https://galaxy.ansible.com/api/v2/collections
     -r {{ automationhub_tempdir.path }}/requirements.yml
     --distribution community
     --repository community
  become: true
  become_user: '{{ pulp_user }}'
  environment:
    PULP_SETTINGS: "{{ pulp_settings_file }}"
```
